baseURL = "http://GatiAher.github.io"
title = "Gati Aher's Blog"
publishDir = "docs"

languageCode = "en-us"
copyright = ""

[author]
    name = "Gati Aher"

[params]
    dateFormat = "Jan 2, 2006"
    description = "I am currently studying computer science at Olin College of Engineering, class of 2023. I use this blog to document my software projects, share my data analysis adventures, and reflect upon design processes."
    images = ["/img/cover_page.png"]

# See https://feathericons.com/
# The value of pre is the icon name
[menux]
  [[menu.main]]
    name = "All Projects"
    pre = "archive"
    url = "/projects"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags"
    weight = 1
  [[menu.main]]
    name = "Contact"
    pre = "at-sign"
    url = "/about"
    weight = 2

[footer]
  [[footer.main]]
    name = " "
    pre = "github"
    url = "https://github.com/GatiAher"
    weight = 1
  [[footer.main]]
    name = ""
    re = "linkedin"
    url = "https://www.linkedin.com/in/gatiaher"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"

[imaging]
bgColor = "#777777"